//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTests.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_user_work
    {
        public long id_user_work { get; set; }
        public string name_work { get; set; }
        public Nullable<long> id_user { get; set; }
        public Nullable<long> id_event { get; set; }
    
        public virtual Db_event Db_event { get; set; }
        public virtual Db_user Db_user { get; set; }
    }
}
