//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Db_user_timestamp
{
    public long id_user_timestamp { get; set; }
    public string user_timestamp { get; set; }
    public Nullable<long> id_user { get; set; }

    public virtual Db_user Db_user { get; set; }
}
